name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: luna983/stitch-aerial-photos:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: setup
        run: |
          echo "---- setup ----"
          python -V
          python -c "from cv2.xfeatures2d import SURF_create"

      # Runs a set of commands using the runners shell
      - name: pytest
        run: |
          echo "---- pytest ----"
          pytest src

      # Runs a set of commands using the runners shell
      - name: flake8
        run: |
          echo "---- flake8 ----"
          flake8 main.py
          flake8 src
